apictl/Makefile
apictl/cmd/clientVersion.go
apiserver/Dockerfile
apiserver/Makefile
apiserver/build.sh
apiserver/kube/kube.go
apiserver/server.go
apiserver/types/types.go
apiserver/version.go

Added "shared config" support to the service spec. This way, a dependent service can access configuration information from another service (e.g., Dataverse can access the iCAT user/password instead of the user needing to add it twice).   Additional changes to the go binary naming conventions -- os/arch in the binary name instead of the path.

Shared config support

---

apiserver/server.go
apiserver/version.go

Updated API server to no longer enforce unique stack and volume names, since IDs are unique.

NDS-181: Stop enforcing unique volume and stack names

---

gui/js/app/expert/modals/configWizard/ConfigurationWizardController.js

See https://opensource.ncsa.illinois.edu/jira/browse/NDS-218
Fixes #35 
Changes:
* configWizard's "config" page should now show when it is needed, regardless of the number of optional services available

NDS-218: Wizard page assumptions can prevent user from entering configuration

---

apiserver/middleware/no_cache.go
apiserver/server.go

Added cache-control response headers to prevent IE from making our service look bad.

Added no-cache headers for NDS-287

---

apictl/client/client.go
apictl/cmd/get.go
apiserver/etcd/etcd.go
apiserver/server.go
apiserver/types/types.go

* Add new GetVocabulary method to API server 
* Vocabularies are loaded from "vocab" subdirectory of ndslabs-specs repository.  Currently, there is a single "tags.json" vocabulary.

Added support for simple vocabulary for tags

---

apiserver/Dockerfile
apiserver/kube/kube.go
apiserver/server.go

* Kubernetes services are now created/deleted during PostStack/DeleteStack operations. This means that the IP address and NodePort remains the same across restarts.
* No longer create NodePorts if API server is configured to use the loadbalancer

NDS 384: Services are created/deleted during add/remove stack

---

apiserver/cmd/server/server.go

* Set system default timeout to 600 seconds when no readiness probe specified.
* Kubernetes FailedSync and Backoff warnings are now reported as errors

NDS 536: Default timeout and "Failed Sync" errors

---

apiserver/cmd/server/server.go

* NDS-577: Added /healthz endpoint that checks etcd, kubernetes API, and gluster availability
* NDS-584: Forgot password for invalid user returns 404
* NDS-552: Added CORS host for <host>.

NDS-577/584/552: Healthz and bug fixes

---

apiserver/Dockerfile
apiserver/cmd/server/server.go
apiserver/pkg/kube/kube.go
apiserver/pkg/types/types.go

* Added support for config.setTo
* Changed config.useFrom to use key.ENV_VAR format
* Fixed bug with creation of Kubernetes resource limits where requests were using max cpu/memory instead of default cpu/memory.
* NDS-631: Delete basic auth annotations from ingress when secure=false

NDS-601: setTo config support

---

apiserver/cmd/server/server.go

* Added default storage quota during admin user creation

NDS-619: Admin user didn't have default storage quota

---

apiserver/cmd/server/server.go
apiserver/pkg/kube/kube.go

* Ingress rules don't exist for services with access=internal.
* Added check during update of secure flag to not try to update ingress rule
* NDS-372: Removed EOF error logging for now

NDS-651 Fixed error when updating non-existing ingress rule 

---

gui/app/catalog/addOrEdit/AddOrEditSpecController.js
gui/app/catalog/addOrEdit/addOrEditSpec.html

Change the UI to replace a value of "" in contextPath with "/"
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-623

NDS-623: Many specs with HTTP ports are missing context paths

---

apiserver/cmd/server/server.go
apiserver/pkg/types/types.go

https://opensource.ncsa.illinois.edu/jira/browse/NDS-970
* Added defaultPath to volumemount in service spec.  If set, the default path is used instead of "AppData"

NDS-970: Added defaultpath for volume mounts

---

apiserver/cmd/server/server.go
apiserver/entrypoint.sh
apiserver/pkg/config/config.go

* Added second HTTP endpoint to apiserver app to handle trusted requests, by default listens on 30002
* Parameterized auth signin/auth URLs used for ingress creation 
* Added RegisterUserOauth  endpoint to serve as upstream from oauth2 proxy, receive request, process headers, create/update account, create JWT cookie, redirect.

NDS-1116: Adds oauth endpoint to apiserver

---

.travis.yml

As part of [NDS-1151](https://opensource.ncsa.illinois.edu/jira/browse/NDS-1151) I created a Travis-CI build attached to this repo. Development of the definitive `.travis.yml` has been slow due to ongoing changes to the nds labs deploy tools. In the mean time, builds in master have generated broken builds in Travis.
I created a simplified `.travis.yml` that just builds the docker image which requires a successful compile of the application code. This is a pretty good first test and the build now succeeds. 
I would like to merge this into master and then put the bigger travis build into the backlog to address once the deploy process settles down.
Visit the travis dashboard for the [NDS Labs project](https://travis-ci.org/nds-org/ndslabs/branches). Select _Trigger Build_ from the menu and …

Create simple travis script to verify basics

---

apiserver/apiserver.json
apiserver/cmd/server/server.go
apiserver/entrypoint.sh
apiserver/pkg/config/config.go
apiserver/pkg/kube/kube.go

Fixes https://github.com/cheese-hub/cheesehub/issues/18
Add a config option to `apiserver.json` to allow the user to override the `nodeSelector` assigned to spawned applications/stacks.
1. Clone / checkout this branch
2. `./build.sh local`
3. Update `apiserver.json` to point at your Kubernetes API, clear out the values for `nodeSelectorName` / `nodeSelectorValue`
* This should run stacks/applications on **any** node
4. Start your apiserver, then switch to a second terminal
5. Run the tests in the `postman/` directory in your second terminal, then switch to a third terminal
6. While the tests are running in the background, use your third terminal to `kubectl get pods -n test --watch`
* Wait for the tests to enter the "StartStack" test case
* You should see a pod appear under the result for …

Allow user to configure nodeSelector for Workbench API server

---

apiserver/apiserver.json
apiserver/cmd/server/server.go
apiserver/entrypoint.sh
apiserver/pkg/config/config.go
apiserver/pkg/kube/kube.go
apiserver/postman/Workbench.postman_collection.json
apiserver/postman/Workbench.postman_collection_local.json

Fixes #249. Workbench currently relies on an admittedly fragile storage model.
Currently, we run GlusterFS in a set of server pods (even-numbered) on our storage nodes. On every node in the cluster we run a Gluster client pod as well. The client pod reaches out to the server pods to mount the Gluster volume onto the host machine from within the container.
The reasoning behind this approach was our requirement for ReadWriteMany volume support, and the lack for such support in our initial OpenStack environments. 
Now that we have more thoroughly explored PVC support in OpenStack environments without making any assumptions about underlying infrastructure, our cup runneth over with different ways to support dynamically-provisioned ReadWriteMany storage using PVCs.
This new approach does away …

Support real PVCs as a replacement GLFS + hostPath

---

apiserver/Dockerfile
apiserver/pkg/kube/kube.go

* Added the volume.beta.kubernetes.io/nfs-mount-path annotation to the PersistentVolumeClaim
* Updated the base containers to Debian Stretch for apiserver

Added the volume.beta.kubernetes.io/nfs-mount-path annotation to the PersistentVolumeClaim

---

apiserver/cmd/server/server.go

The go client returns empty objects on error, so current checks that look for nil objects fail.

Check for error, not nil service

---

apiserver/cmd/server/server.go
apiserver/pkg/kube/kube.go
apiserver/pkg/types/types.go
apiserver/test/services/test/full.json

We currently only have 2 levels of security: `default` and `privileged`. Since Kubernetes supports very fine-grained security features, we should support those individually.
Fixes #266 
Replace `privileged` boolean on our Spec object with a `securityContext` field that can be passed directly through to Kubernetes.
NOTE: Since this is an admin-only field, there is no API validation or UI component to this PR.
1. `minikube start`
2. `docker run --name=etcd -p 4001:4001 -d ndslabs/etcd:2.2.5  /usr/local/bin/etcd \
--bind-addr=0.0.0.0:4001 \
--advertise-client-urls=http://127.0.0.1:4001`
3. Configure `apiserver.json` to point to minikube and etcd
4. Checkout, build branch locally, then run: `./build.sh local && ./build/bin/apiserver-darwin-amd64`
5. Use Postman to login as the admin, change …

Support finer grained security capabilities

---

apiserver/build.sh

API server takes several minutes to build a one-line change. This is partially due to the fact that we always re-pull our vendor dependencies with `glide`, even if they have not changed.
Add an optional `--cache` flag that will signal to skip pulling the vendor dependencies. This way, we can skip directly to building the binaries if we haven't added any new dependencies.
Note that by default (e.g. during DockerHub build), dependencies will be pulled
1. Checkout this branch locally
2. Change directories to `ndslabs/apiserver/`
3. Execute `./build.sh local`
* You should see `Fetching dependencies...`, followed by the usual `glide` fetch output
4. Now execute `./build.sh local --cache`
* You should immediately see `Building apiserver-darwin-amd64` with no reference to fetching dependencies

Speed up local apiserver builds with optional flag for fetching dependencies

---

apiserver/cmd/server/server.go
apiserver/pkg/kube/kube.go
apiserver/pkg/types/types.go
apiserver/pkg/version/version.go

Fixes https://github.com/nds-org/ndslabs/issues/277.
**Description:** 
The [CHEESEHub ArpSpoof](https://github.com/cheese-hub/arpspoof) scenario requires that all services within the stack run on the same node.  This PR adds support for pod affinity for services in a stack with the `collocate` configuration option.  If `collocate` is set to true on a service, then pod-level affinity is enabled using the stack label.
**Test**
Below is a full functional test using a multi-node cluster.  A cluster is currently deployed on IU Jetstream as https://www.test.cheesehub.org.
1. Provision 2-worker + 1 storage cluster using https://github.com/nds-org/kubeadm-terraform `weave-fix` branch.
2. Configure https://github.com/nds-org/workbench-helm-chart
3. Use https://github.com/craig-willis/catalog.git …

Add option to ensure services run on the same node

---

apiserver/Dockerfile
apiserver/pkg/kube/kube.go

The exec (console) function was never implemented in the go client migration.  This PR fixes that.

Implemented exec using go client

---

apiserver/cmd/server/server.go
apiserver/pkg/config/config.go

Fixes #289 
This adds the QPS and Burst configuration overrides for the kube client. I've set defaults at 50/100, which works for the CHEESEHub case.
To test:
* Deploy this apiserver
* Run the https://github.com/cheese-hub/loadtest

Added QPS and Burst overrides

---

gui/dashboard/catalog/CatalogController.js
gui/dashboard/dashboard/DashboardController.js
gui/dashboard/dashboard/dashboard.html

We currently have no way of tracking user actions within the system. That is, given a set of users exercising the system, we are unable to track history of which applications were run or which actions were performed.
Moreover we have no way of knowing when users are encountering issues with a particular application.
Fixes #294 
Add simple event tracking to monitor which buttons the user pushes on the Workbench Dashboard. 
We can now track:
* page views (present previously)
* adding an application from the catalog
* deleting your instance of an application
* starting / stopping an application
* viewing logs/config/console for an application's service
* editing an application's service
NOTE: If we can think of other low-hanging analytics to track here, I am open to further suggestions :+1: …

Analytics event tracking

---

gui/dashboard/catalog/CatalogController.js
gui/dashboard/catalog/catalog.html
gui/dashboard/dashboard/dashboard.html
gui/landing/landing.html
gui/shared/navbar/navbar.html

Fixes #306 
Fixes #307 
Fixes #308 
Fixes #309 
Fixes #310 
Fixes #311 
Follow the guidelines laid out by the SGCI feedback from the UI / UX Usability Study.

Address SGCI Phase 2 Feedback

---

apiserver/.dockerignore
apiserver/.gitignore
apiserver/Dockerfile
apiserver/apiserver.json
apiserver/build.sh
apiserver/cmd/server/server.go
apiserver/entrypoint.sh
apiserver/glide.lock
apiserver/glide.yaml
apiserver/pkg/config/config.go
apiserver/pkg/kube/kube.go
apiserver/pkg/version/.gitignore

We have decided to use `cert-manager`, but our current Ingress creation logic is missing some necessary changes.
* Read ISSUER / CLUSTER_ISSUER from envvar, add this as annotation to Ingress rules as we create them
* ~~Added `secretName` to `tls` section~~ We can reuse the same secret across namespaces, like we used to
* Change `tls.host` to be `*.$DOMAIN`, instead of an explicit domain 
* Update `apiserver` to use golang 1.15 / Debian Buster
* Added missing build dependency for `github.com/docker/spdystream`
* Reorder/refactor Docker file to take advantage of layer caching
See Test Case for https://github.com/nds-org/workbench-helm-chart/pull/21

Support cert-manager, fix apiserver build dependencies

---

apiserver/Dockerfile

A recent PR has inadvertently moved the location of the templates used to send automated e-mails.
Fix the output directory back to `/templates`
1. Deploy Helm chart running this `apiserver` image
2. Sign up for a new account
* You should **not** get an error saying that every username has already been taken

Fix email template output directory

---

apiserver/cmd/server/server.go

`apiserver` becomes very stable when starting or stopping stacks seemingly at random. My suspicion is that `etcd` sometimes gets overwhelmed and requests will timeout, as we occasionally see warnings of this in the logs. If not handled properly, these errors can crash the golang code.  
Improve start/stop stack error-handling by simply ignoring these types of timeouts.
NOTE: Since the problem is intermittent, it is hard to reproduce reliably
1. Deploy this `workbench.image.apiserver` via the Helm chart: `ndslabs/apiserver:start-stop-error-handling`
2. Start and stop a bunch of stacks - really test out the system
* You should get some warning about etcd header timeouts, but the `apiserver` should no longer crash and trigger a container restart

Improve error-handling around starting/stopping stacks

---

apiserver/Dockerfile
apiserver/pkg/apictl/cmd/add.go

Add account (admin only) creates users with a blank `status`.
Also, our golang imports/package names need to be updated to point at this new repo.
* Set `status` to approved when using the admin-only `ndslabsctl add account` function
* Fix all of our locally-imported packages to point at new repo
1. Deploy the Helm chart with `workbench.images.apiserver=ndslabs/apiserver:fix-ndslabsctl-add-account`
2. Fetch the "admin" user password: `kubectl exec -it deploy/workbench -c apiserver -- cat password.txt`
* Copy this password to your clipboard
3. Login as the admin user with this password: `kubectl exec -it deploy/workbench -c apiserver -- ndslabsctl login admin`
* Paste the password from your clipboard
* You should see "Login succeeded"
4. Add the demo account via file: `kubectl exec -it …

Fix ndslabsctl add account to also approve the new user

---

apiserver/.dockerignore
apiserver/Dockerfile
apiserver/build.sh
apiserver/cmd/server/server.go
apiserver/entrypoint.sh
apiserver/pkg/kube/kube.go
gui/Dockerfile
gui/Dockerfile.ng-base
gui/dashboard/DashboardModule.js
gui/server.js
gui/shared/navbar/NavbarController.js
gui/swagger.yaml

SSO is fragile and/or not working. We would like to harden this a bit and add some level of support for logging in with CILogon.
Fixes #254
* Support oauth2 proxy + Keycloak + CILogon configuration
* Add a new endpoint that will validate the `_oauth2_proxy` cookie / session data and use it to ensure that an account is created for the user in Workbench, then issue a JWT for the user
* Add logic in the dashboard UI module that will send the `_oauth2_proxy` cookie to the new endpoint mentioned above if the user reaches a protected part of the dashboard without a valid JWT
Other minor changes include:
* Speed improvements for `apiserver` and `gui` Docker image builds
* Upgrade `ng-base` Docker image from `xenial` -> `focal` (Ubuntu 20.04 LTS) and `carbon` -> `erbium`(NodeJS 12 LTS)
* Cut down …

Testing / enhancing oauth integration

---

apiserver/templates/demo-account.json

Creating a demo account is a hassle
Include a `templates/demo-account.json` in the container to make it easier to get a test user registered

Add a demo account template inside the container

---

gui/swagger.yaml

There was an error in schema validation for `swagger.yaml`
```
{"messages":["attribute paths.'/start'.[key].schema is unexpected","attribute paths.'/start'.[key].type is missing"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"oneOf","message":"instance failed to match exactly one schema (matched 0 out of 2)","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/parametersList/items"},"instance":{"pointer":"/paths/~1start/parameters/0"}}]}
```
What this means is that `schema` should not be used in `/start`, as it does not point to a type that we have defined. Instead, to use the built-in `type` of `string`, we must not say we are specifying a schema.
* Remove `schema.type` and use `type` directly

Fix validation error in swagger.yaml

---

apiserver/cmd/server/server.go
gui/dashboard/dashboard/dashboard.html

When using OAuth, we take verbatim the user's username or email prefix as the Workbench username. This is problematic when the email address contains special characters, which are allowed as email addresses but not as the name of a k8s-namespace or resource
Strip special chars from username before creating it in the system.
1. Sign-up a Google account with special chars in the username
2. Log into Workbench
3. Verify that namespace / PVC were created as expected
4. Launch an application to verify that account is working

Strip special chars from username

---

gui/entrypoint.sh

If no HelpLinks were specified, the `env.json` produced is not valid. This causes anything that relies on env.json to fail:
* Poduct Name / navbar brand logo
* Help links
* Learn more button on landing page
Use `[]` as default value in this case, instead of empty string

Fix bad format when HelpLinks are not provided (default case)

---

apiserver/cmd/server/server.go
apiserver/entrypoint.sh

Issues found during migration / testing of the TERRA-REF Workbench
A feature was added in ~2017 to mount the user's entire PVC into their workbench app (defaultPath = "/")
eventually, defaultPath maps down to `subPath` in the Kubernetes volume spec
Sometime in ~2018, a vulnerability was discovered in Kubernetes that required `subPath` to be a relative path for security reasons. I suspect this this has been missed for so long because it is a unique edge case.
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-970
See https://kubernetes.io/blog/2018/04/04/fixing-subpath-volume-vulnerability/

Fix handling for defaultPath="/", configure apiserver loglevel at runtime

---

apiserver/pkg/kube/kube.go

Ingress Controller creates rules with auth annotations that are specific to NGINX. This breaks support for Traefik, where we need slightly more general annotations to cover more possible ingress controllers
* Change `nginx.ingress.kubernetes.io` -> `ingress.kubernetes.io` throughout
* Add new annotation: `ingress.kubernetes.io/auth-type=forward` - enable forwardAuth in Traefik and possibly other providers
* Added a note about revisiting NetworkPolicies (currently disabled, but they appear to also contain references and patterns specific to NGINX, and may be completely outdated)

Better support for Traefik and other ingress controllers

---

apiserver/cmd/server/server.go
apiserver/pkg/kube/kube.go

There is a mysterious problem with the PDG cluster where sometimes namespaces (and PVCs and ResourceQuotas) fail to create when a new user logs in for the first time.
It is still unclear if the namespace existence is preventing the other resources, or if there is another problem that is affecting those resources
Add some logging for the error case(s) during `setupAccount` - this should at least tell us why the namespace fails to create

Add error logging during setupAccount (don't fail)

---

README.md

* Stale links to golang repo in `README.md`
* ~~Stale Swagger spec in `apis/`~~
* Change `golang` -> `python` in links in `README.md`
* ~~Update Swagger spec with latest version from https://github.com/nds-org/workbench-apiserver-python~~ already handled

fix: update stale links in README
