- gui/Dockerfile.ndslabs-gui
- gui/js/app/expert/ExpertSetupController.js
- gui/js/app/expert/modals/configViewer/configViewer.html
- gui/js/app/expert/modals/configWizard/ConfigurationWizardController.js
- gui/js/app/expert/modals/stackStop/stackStop.html
- gui/js/app/login/modals/signUp/SignUpController.js
- gui/release.sh
Resolves the front-end portion of issue #5
> Use id for attach / delete volume in GUI

- gui/js/app/shared/filters.js
This should resolve the front-end portion of issue #6
> 'isStack','isStandalone' -> display in GUI

- apiserver/Dockerfile
- apiserver/build.sh
- apiserver/server.go
- apiserver/version.go
Changed the base image for apiserver, built new apiserver with fixes for #10
> Minor build changes, fix #10

- gui/js/app/expert/expertSetup.html
- gui/js/app/expert/modals/configWizard/ConfigurationWizardController.js
- gui/js/app/expert/modals/configWizard/configurationWizard.html
- gui/js/app/shared/filters.js
> Orphaned volumes add to 'Projected Usage'

- gui/js/app/app.js
> Squelch debug logging

- gui/Dockerfile.ndslabs-gui
- gui/build.sh
- gui/js/app/app.js
- gui/js/app/expert/modals/configWizard/ConfigurationWizardController.js
- gui/js/app/expert/modals/configWizard/configurationWizard.html
- gui/js/app/login/LoginController.js
- gui/release.sh
- gui/start.sh
- gui/swagger.sh
Resolves issue #26
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-170
> NDS-170: User's session can timeout while configuring a new stack

- apiserver/etcd/etcd.go
- apiserver/version.go
Fixed in container build ndslabs/apiserver:NDS-215
> NDS-215: API server throws 500 on GetVolumes

- gui/Dockerfile.ndslabs-gui
- gui/build.sh
- gui/js/app/app.js
- gui/js/app/expert/ExpertSetupController.js
- gui/js/app/expert/expertSetup.html
- gui/js/app/expert/modals/configWizard/ConfigurationWizardController.js
- gui/js/app/shared/filters.js
- gui/js/app/shared/services.js
- gui/js/asset/css/suppl.css
- gui/js/index.html
- gui/release.sh
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-216
A test Docker image containing these changes can be found on Docker Hub: [ndslabs/ndslabs-gui:NDS-216](https://hub.docker.com/r/ndslabs/ndslabs-gui/tags/).
Modifications:
* Moved server data queries into their respective factories
* Abstracted soft-refresh logic into its own factory
* Abstracted auto-refresh logic into its own factory
Also:
* Lowered token_check interval from 3 minutes to 1 minute
* Fixed "mailto:" link URL encoding
* Added some CSS to (hopefully) allow us to use [ngCloak](https://docs.angularjs.org/api/ng/directive/ngCloak)
* Slight updates to GUI build / release scripts
> NDS-216: UI should stop auto-refresh when user's token expires

- gui/api/generate-angular.js
- gui/js/app/app.js
- gui/js/app/expert/modals/configWizard/ConfigurationWizardController.js
- gui/js/app/expert/modals/configWizard/configurationWizard.html
- gui/js/app/shared/filters.js
- gui/js/app/shared/services.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-182
Fixes #21 
Changes:
* Removed validation constraint on stacks: unique name
* Removed validation constraint on volumes: unique name
* Removed some stray **debugger** and **console** statements
* Fixed storage quota calculation
* Fixed storage quota validation during multiple volume setup
> NDS-182: GUI should not enforce unique names for stacks / volumes

- apictl/cmd/clientVersion.go
- apictl/cmd/root.go
- apiserver/build.sh
- apiserver/entrypoint.sh
- apiserver/kube/kube.go
- apiserver/server.go
- apiserver/types/types.go
- apiserver/version.go
* Added Prefix option to apiserver.conf, defaults to "/api"
* Added PREFIX env var to entrypoint.sh
* Updated Port and Readiness probe types to reflect changes to Kubernetes API (int > int32)
> Added Prefix config option

- apiserver/server.go
Updated apiserver/server.go to include the project namespace in the volume path when creating volumes
> Added namespace to volumes path

- apiserver/server.go
This is a quick-and-dirty approach to adding Kubernetes event messages to the NDS Labs logs.
> Added stack service status messages to logs

- gui/js/app/expert/expertSetup.html
- gui/js/app/shared/navbar/navbar.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-276
> NDS-276: UI displays project namespace where name expected

- gui/js/app/expert/expertSetup.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-268
> NDS-268: User can stop stack in error state

- gui/js/app/shared/services.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-291
> NDS-291: Race condition in UI prevents showing stack service name when running off-site

- apictl/build.sh
- apiserver/Godeps/Godeps.json
- apiserver/Godeps/Readme
- apiserver/apiserver.conf
- apiserver/build.sh
- apiserver/entrypoint.sh
- apiserver/gobuild.sh
- apiserver/server.go
* Implemented default resource limits
* Added much needed godeps support
> NDS-314: Default resources limits and Godeps

- gui/js/app/expert/ExpertSetupController.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-273
> NDS-273: Volume information is not refreshed when optional services removed

- gui/Dockerfile.ndslabs-gui
- gui/entrypoint.sh
- gui/js/app/app.js
- gui/js/app/expert/addService/AddServiceController.js
- gui/js/app/expert/configWizard/ConfigurationWizardController.js
- gui/js/app/expert/expertSetup.html
- gui/js/app/login/signUp/SignUpController.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-313
> NDS-313: Change default storage handling - GUI

- apictl/client/client.go
- apictl/cmd/add.go
- apictl/cmd/attach.go
- apictl/cmd/clientVersion.go
- apictl/cmd/console.go
- apictl/cmd/create.go
- apictl/cmd/delete.go
- apictl/cmd/detach.go
- apictl/cmd/get.go
- apictl/cmd/list.go
- apictl/cmd/logs.go
- apictl/cmd/passwd.go
- apictl/cmd/set.go
- apictl/cmd/start.go
- apictl/cmd/stop.go
- apictl/test/account.json
- apis/swagger-spec/ndslabs.json
- apis/swagger-spec/ndslabs.yaml
- apiserver/etcd/etcd.go
- apiserver/kube/kube.go
- apiserver/server.go
- apiserver/test/accounts/account-limited.json
- apiserver/test/projects/project.json
- apiserver/types/types.go
Note, this includes updates to the ndslabsctl 
* Removed /projects API paths,  /projects/* is now /stacks, /volumes, /logs, etc.
* Changed "Project" to "Account" 
* Removed "pid" parameter, instead now rely on userId stored in auth token
* Added support for user-specific and system catalog
> Add support for user service catalog, change "projects" to "accounts", remove "pid" requirement from API

- gui/js/app/app.js
- gui/js/app/appStore/CatalogController.js
- gui/js/app/shared/filters.js
- gui/start.sh
Very suddenly, the "_.matchesProperty" shorthand iteratee stopped working in lodash.
More investigation is needed as to why this just happened out from underneath me...
> Corrected lodash shorthand

- gui/js/app/appStore/CatalogController.js
- gui/js/app/shared/filters.js
- gui/js/index.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-415
> NDS-415: lodash 4.5.1 _.matchesProperty iteratee shorthand is suddenly broken

- gui/Dockerfile
- gui/build.sh
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-306
> NDS-306: Docker builds sourcing base image tag :latest is non-deterministic

- gui/js/app/appStore/CatalogController.js
- gui/js/app/dashboard/service/AddOrEditServiceController.js
- gui/js/app/shared/services.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-398
> NDS-398: UI should automatically generate secure random passwords where necessary

- gui/js/app/appStore/addOrEdit/AddOrEditSpecController.js
- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
- gui/js/asset/css/suppl.css
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-412
> NDS-412: Cloned specs cause ambiguity in the Add/Edit Spec Dependency List

- gui/js/app/appStore/CatalogController.js
- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
- gui/js/app/appStore/catalog.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-390
> NDS-390: Edit / Delete Spec should be disabled when a stack exists of that spec

- gui/js/app/appStore/addOrEdit/AddOrEditSpecController.js
- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
- gui/js/app/appStore/catalog.html
- gui/js/app/shared/filters.js
- gui/js/app/shared/services.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-397
> NDS-397: Add missing fields to the 'Edit Spec' view

- apiserver/kube/kube.go
- apiserver/server.go
- apiserver/types/types.go
* Add NDSLABS_HOME to all containers
* NDS-435: Change image pull policy to always
* Added "info" to spec
> NDS 416: Add NSDLABS_HOME to containers

- gui/Dockerfile
- gui/js/app/appStore/addOrEdit/AddOrEditSpecController.js
- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
- gui/js/app/appStore/catalog.html
- gui/js/app/shared/directives.js
- gui/js/app/shared/services.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-387
> NDS-387: "New XXX" forms in Add/Edit Spec view should validate user input

- apiserver/kube/kube.go
- apiserver/server.go
- apiserver/types/types.go
* Remove name field from volumeMount
* Added type field (docker) for docker socket mounts (still no permission checking)
> NDS-423: Removed volumeMount name field, added type (docker)

- apictl/cmd/add.go
- apiserver/kube/kube.go
- apiserver/server.go
- apiserver/types/types.go
* Added privileged attribute to service spec object. If set, securityConstraint.Privileged=true set on container
* Privileged attribute is ignored for services deployed to the user catalog
> NDS-439: Added privileged container support

- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-447
> NDS-447: Remove 'Volume Name' field from Add / Edit Spec view

- gui/js/app/appStore/catalog.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-448
> NDS 448: Change Add to Create at top-right of AppStore view

- apictl/client/client.go
- apictl/cmd/rename.go
- apis/swagger-spec/ndslabs.json
- apis/swagger-spec/ndslabs.yaml
- apiserver/server.go
* Updated swagger spec
* Added PUT /stacks/{stackid}/rename 
** { "name": "newname"}
* Added CLI rename command
> NDS-394: Added rename endpoint

- gui/api/ndslabs.json
- gui/api/package.json
- gui/js/app/dashboard/modals/stackRename/StackRenameController.js
- gui/js/app/shared/api.js
- gui/swagger.sh
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-451
> NDS-451: Hook up to new rename stack API endpoint

- gui/js/app/dashboard/dashboard.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-432
> NDS-432: StackService list not displaying multiple endpoints

- gui/js/app/dashboard/DashboardController.js
- gui/js/app/dashboard/dashboard.html
- gui/js/app/shared/navbar/navbar.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-442
> NDS-442: User should be able to launch/navigate to their FileManager

- gui/js/app/login/LoginController.js
- gui/js/app/login/signUp/SignUpController.js
- gui/js/app/shared/services.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-255?focusedCommentId=45181&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-45181
> NDS-255: Passwords should not be returned in plaintext

- apictl/client/client.go
- apictl/cmd/add.go
- apictl/cmd/console.go
- apictl/cmd/delete.go
- apictl/cmd/get.go
- apictl/cmd/list.go
- apictl/cmd/login.go
- apictl/cmd/logs.go
- apictl/cmd/rename.go
- apictl/cmd/set.go
- apictl/cmd/start.go
- apictl/cmd/stop.go
- apiserver/Dockerfile
- apiserver/entrypoint.sh
- apiserver/server.go
* Create real admin account during server startup, if not present
* Set password via entrypoint.sh ADMIN_PASSWORD env var
* Change CLI to no longer prompt for admin user for restricted tasks
> NDS-418: Real admin account

- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
- gui/js/app/appStore/catalog.html
- gui/js/app/login/signUp/signUp.html
- gui/js/app/login/verify/VerifyAccountController.js
- gui/js/app/login/verify/verify.html
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-436
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-470
> NDS-436 / NDS-470

- gui/js/app/dashboard/dashboard.html
- gui/js/app/shared/filters.js
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-456 (already fixed)
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-469
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-475
> NDS-475 / NDS-469 / NDS-456

- gui/js/app/app.js
- gui/js/app/appStore/catalog.html
- gui/js/app/dashboard/DashboardController.js
- gui/js/app/shared/loading.html
- gui/js/app/shared/navbar/navbar.html
- gui/js/app/shared/services.js
- gui/js/asset/css/suppl.css
- gui/js/bower.json
- gui/js/index.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-245
> NDS-245: UI does not indicate when it is loading data

- apictl/cmd/add.go
- apiserver/crypto/crypto.go
- apiserver/etcd/etcd.go
- apiserver/glide.lock
- apiserver/glide.yaml
- apiserver/kube/kube.go
- apiserver/server.go
- apiserver/types/types.go
* Added Secure flag to stack object
* Added --secure flag to ndslabsctl add stack command
* Create/update basic-auth secret when account updated or password changed
* Added auth annotations to ingress object
* Changed password storage to Apache apr1, which is required by the official nginx ingress controller.
> NDS-308: Added basic auth support

- apictl/client/client.go
- apictl/cmd/support.go
- apis/swagger-spec/ndslabs.yaml
- apiserver/email/email.go
- apiserver/entrypoint.sh
- apiserver/server.go
- apiserver/templates/new-account-request.html
- apiserver/templates/support-request.html
- apiserver/types/types.go
* POST /support sends email to NDS Labs support 
* GET /contact returns contact information map
> NDS 490: Support requests and contact info

- gui/api/ndslabs.yaml
- gui/js/app/app.js
- gui/js/app/appStore/catalog.html
- gui/js/app/help/HelpController.js
- gui/js/app/help/help.html
- gui/js/app/login/LoginController.js
- gui/js/app/login/reset/ResetPasswordController.js
- gui/js/app/shared/api.js
- gui/js/app/shared/navbar/navbar.html
- gui/js/asset/css/suppl.css
- gui/js/index.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-183
> NDS-183: User should be able to provide feedback for NDS Labs

- apiserver/cmd/server/server.go
- apiserver/entrypoint.sh
- apiserver/pkg/kube/kube.go
* Added NDSLABS_HOSTNAME, NDSLABS_DOMAIN and NDSLABS_EMAIL env vars
* Changed default shell from bash to sh
> NDS 511: Added hostname, email address, change default shell to sh

- apiserver/cmd/server/server.go
- apiserver/pkg/kube/kube.go
- apiserver/pkg/types/types.go
* Removed sharedConfig
* If Config.useFrom set, during StartController (i.e., startStack), set the value.
* useFrom services must exist during put/post service
> NDS-523: Added Config.UseFrom support

- gui/js/app/app.js
- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
- gui/js/app/appStore/catalog.html
- gui/js/app/dashboard/console/ConsoleController.js
- gui/js/app/dashboard/console/console.html
- gui/js/app/dashboard/dashboard.html
- gui/js/app/dashboard/service/AddOrEditServiceController.js
- gui/js/app/dashboard/service/addOrEditService.html
- gui/js/app/help/HelpController.js
- gui/js/app/help/help.html
- gui/js/app/login/reset/reset.html
- gui/js/app/login/signUp/SignUpController.js
- gui/js/app/login/signUp/signUp.html
- gui/js/app/login/verify/verify.html
- gui/js/app/shared/navbar/NavbarController.js
- gui/js/app/shared/navbar/navbar.html
- gui/js/index.html
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-549
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-551
> NDS-549 / NDS-551

- gui/js/app/appStore/CatalogController.js
- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
- gui/js/app/appStore/catalog.html
- gui/js/app/appStore/modals/export/ExportSpecController.js
- gui/js/app/dashboard/dashboard.html
- gui/js/app/dashboard/modals/configViewer/configViewer.html
- gui/js/app/dashboard/service/AddOrEditServiceController.js
- gui/js/app/dashboard/service/addOrEditService.html
- gui/js/app/shared/filters.js
- gui/js/asset/css/suppl.css
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-497
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-502
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-503
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-516
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-543
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-544
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-545
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-546
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-547
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-548
> A big pile of tiny UI updates

- apiserver/cmd/server/server.go
- apiserver/pkg/kube/kube.go
* NDS-466: Re-enabled storage quotas
* NDS-501: include stack name in AppData dir
* NDS-513: Check dependencies exist on Post/Put service
* NDS-538: Added NDSLABS_STACK environment variable
* NDS-541: Fixed problem with ingress object name
> NDS-466/501/513/538/541: Re-enable quotas, AppData dir, check dependencies, ingress delete problem

- apiserver/cmd/server/server.go
- apiserver/pkg/apictl/cmd/get.go
- apiserver/pkg/validate/validate.go
* NDS-500: Return 403 on delete admin account
* NDS-531: Check key length on Put/PostService
* NDS-558: CLI bug on get account
* NDS-537: Stack won't stop when dependency in error state
> NDS 500/531/537/558: API server bugs

- apiserver/cmd/server/server.go
- apiserver/pkg/kube/kube.go
* API server creates basic-auth secret in kube-system namespace with same password as admin user.
> NDS-540 / NDS-483: LMA basic auth

- gui/js/app/dashboard/DashboardController.js
- gui/js/app/dashboard/dashboard.html
- gui/js/app/dashboard/service/AddOrEditServiceController.js
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-493
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-515
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-519
> NDS-493 / NDS-515 / NDS-519: AutoRefresh + FileManager bug fixes

- gui/entrypoint.sh
- gui/js/app/app.js
- gui/js/app/appStore/CatalogController.js
- gui/js/app/appStore/addOrEdit/AddOrEditSpecController.js
- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
- gui/js/app/dashboard/DashboardController.js
- gui/js/app/dashboard/console/ConsoleController.js
- gui/js/app/dashboard/service/AddOrEditServiceController.js
- gui/js/app/login/LoginController.js
- gui/js/app/login/signUp/SignUpController.js
- gui/js/app/shared/footer/FooterController.js
- gui/js/app/shared/footer/footer.html
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-506
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-553
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-554
> NDS-506 / NDS-553 / NDS-554: Auth routing + TCP Ports + error banner on api fail

- gui/js/app/app.js
- gui/js/app/dashboard/modals/configViewer/configViewer.html
- gui/js/app/landing/LandingController.js
- gui/js/app/landing/landing.html
- gui/js/app/login/signUp/SignUpController.js
- gui/js/app/login/signUp/signUp.html
See:
* [Add user agreement](https://opensource.ncsa.illinois.edu/jira/browse/NDS-582)
* [Don't show request access/sign in on landing page if signed in](https://opensource.ncsa.illinois.edu/jira/browse/NDS-592)
* [View Config Modal no longer displays external endpoint(s)](https://opensource.ncsa.illinois.edu/jira/browse/NDS-594)
> NDS-582 / NDS-592 / NDS-594: Landing Page, part deux + view config/endpoint bugfix

- gui/js/app/landing/LandingController.js
Accidentally removed a dependency where I ought not have
> Fixed Landing Page's "click here" link

- gui/js/app/appStore/addOrEdit/AddOrEditSpecController.js
- gui/js/app/appStore/addOrEdit/addOrEditSpec.html
- gui/js/app/dashboard/dashboard.html
- gui/js/app/dashboard/modals/configViewer/configViewer.html
- gui/js/app/landing/LandingController.js
- gui/js/app/shared/filters.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-522
> NDS-522: Add default context field for applications not served from root - UI

- gui/app/dashboard/dashboard.html
- gui/app/dashboard/modals/stackStop/stackStop.html
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-606
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-609
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-620
> NDS-609 / NDS-620 / NDS-606: Subtle UX updates

- gui/app/dashboard/dashboard.html
- gui/app/dashboard/service/AddOrEditServiceController.js
- gui/app/dashboard/service/addOrEditService.html
- gui/app/shared/services.js
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-680
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-681
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-682
> NDS-680 / 681 / 682: Various subtle UX tweaks

- gui/app/landing/LandingController.js
See: https://opensource.ncsa.illinois.edu/jira/browse/NDS-638
> NDS-638: Fixed password recovery

- gui/app/dashboard/dashboard.html
- gui/app/dashboard/modals/stackStop/stackStop.html
See:
- https://opensource.ncsa.illinois.edu/jira/browse/NDS-621
- https://opensource.ncsa.illinois.edu/jira/browse/NDS-653
> NDS-621 / 653: Hide internal endpoint links from dashboard / shut down modal

- gui/app/app.js
- gui/bower.json
- gui/entrypoint.sh
- gui/index.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-275
> NDS-275: Support Google Analytics

- gui/app/catalog/addOrEdit/addOrEditSpec.html
- gui/app/catalog/catalog.html
- gui/app/dashboard/dashboard.html
- gui/app/login/signUp/SignUpController.js
- gui/app/login/signUp/signUp.html
- gui/app/shared/navbar/navbar.html
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-661
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-663
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-669
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-670
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-678
> NDS-661 / 663 / 669 / 670 / 678: Minor UX changes

- gui/app/dashboard/DashboardController.js
- gui/app/shared/navbar/NavbarController.js
- gui/app/shared/navbar/navbar.html
- gui/app/shared/services.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-650
> NDS-650: FileManager intermittently fails to launch

- apiserver/cmd/server/server.go
- apiserver/pkg/apictl/client/client.go
- apiserver/pkg/apictl/cmd/add.go
- apiserver/pkg/apictl/cmd/export.go
- apiserver/pkg/apictl/cmd/import.go
- apiserver/pkg/apictl/cmd/stop.go
- apiserver/pkg/types/types.go
* Added import/export endpoints and CLI commands
* Added stop_all endpoint and stop --all CLI command
* Added --user flag to stop command, available only to admin
> NDS-690: Import/export account, stop-all, stop --user

- gui/Dockerfile
- gui/app/api/SwaggerController.js
- gui/app/app.js
- gui/app/catalog/addOrEdit/addOrEditSpec.html
- gui/app/dashboard/dashboard.html
- gui/app/shared/directives.js
- gui/app/shared/navbar/navbar.html
- gui/app/shared/services.js
- gui/entrypoint.sh
- gui/index.html
- gui/package.json
- gui/server.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-507
> NDS-507: Explore log forwarding for NDS Labs UI

- apiserver/pkg/email/email.go
- apiserver/pkg/etcd/etcd.go
- apiserver/pkg/kube/kube.go
- apiserver/templates/new-account-request.html
* NDS-707: log warning when invalid account key found in etcd
* NDS-685: Added username to approval email
* NDS-697: Changed name of basic authentication realm, which doesn't really matter.
> NDS-707/685/697: Multiple bugs

- gui/Dockerfile
- gui/Dockerfile.ng-base
- gui/Gruntfile.js
- gui/entrypoint.sh
- gui/install-headless-deps.sh
- gui/protractor.conf.js
* Fix entrypoint to properly install npm/bower components
* Fix Dockerfile to properly set up jessie-backports
* Fix Gruntfile.js to install headless e2e dependencies for us
* Fix both Dockerfiles to skip installing recommended packages
> Fix broken WebUI on master

- gui/Gruntfile.js
- gui/app/catalog/addOrEdit/addOrEditSpec.html
- gui/app/catalog/modals/clone/cloneSpec.html
- gui/app/catalog/modals/import/importSpec.html
- gui/app/dashboard/modals/stackRename/stackRename.html
- gui/app/help/help.html
- gui/app/login/login.html
- gui/app/login/reset/reset.html
- gui/app/login/signUp/signUp.html
- gui/app/shared/services.js
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-662
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-720
> NDS-720 / NDS-662: Multiple click events fix + FileManager popup fix 

- gui/tests/e2e/pages/addEditService.page.js
- gui/tests/e2e/pages/addEditSpec.page.js
- gui/tests/e2e/pages/catalog.page.js
- gui/tests/e2e/pages/console.page.js
- gui/tests/e2e/pages/dashboard.page.js
- gui/tests/e2e/pages/help.page.js
- gui/tests/e2e/pages/landing.page.js
- gui/tests/e2e/pages/reset.page.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-729
> NDS-729: E2E tests should not assume TLS

- gui/Dockerfile
- gui/Gruntfile.js
- gui/app/app.js
- gui/asset/css/suppl.css
- gui/install-headless-deps.sh
- gui/package.json
- gui/server.js
Added gzip compression and set NODE_ENV to production
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-727
> NDS-727: Address potential performance pitfalls in Express web server

- README.md
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-512
> NDS-512: Update README

- gui/entrypoint.sh
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-510
> NDS-510: Allow user to customize the UI

- gui/package.json
- gui/server.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-744
> NDS-744: Add winston to /logs endpoint for asynchronous logging

- gui/bower.json
* Sorted bower.json dependencies alphabetically
* Roll font-awesome forward to ^4.7.0
See: https://opensource.ncsa.illinois.edu/jira/browse/NDS-807
> NDS-807: Fix missing help icon in navbar

- apiserver/apiserver.json
- apiserver/cmd/server/server.go
- apiserver/entrypoint.sh
- apiserver/pkg/config/config.go
- apiserver/pkg/email/email.go
- apiserver/templates/approved-email.html
- apiserver/templates/denied-email.html
- apiserver/templates/new-account-request.html
- apiserver/templates/recovery-request.html
- apiserver/templates/support-request.html
- apiserver/templates/verified-email.html
- apiserver/templates/verify-email.html
* Added ability to customize support and chat URLs in apiserver.json
* Added ability to customize workbench name in apiserver.json that's used in emails.
> NDS-780/781: Customizable workbench name, forum, and chat URLs

- gui/app/help/HelpController.js
* Changed default support chat/forum/email headers to be more generic
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-781
> NDS-781: Minor cosmetic change to accompany #190

- gui/app/login/signUp/signUp.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-843
> NDS-843: Clarified that usernames must be lowercase

- gui/README.md
* Added some notes about the Git drop-in feature of the UI
> NDS-862: Update gui/README.md

- apiserver/cmd/server/server.go
- apiserver/entrypoint.sh
- apiserver/pkg/apictl/client/client.go
- apiserver/pkg/apictl/cmd/log_level.go
- apiserver/pkg/etcd/etcd.go
* Added log_level endpoint to dynamically change log level
* Added ndslabsctl set log_level command to set log level (admin only)
* Changed default log level to v(1)
> NDS-778: Audit apiserver loggin

- gui/app/catalog/addOrEdit/addOrEditSpec.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-913
> NDS-913: Adding a port on the Add/EditSpec page saves and exits the whole form

- gui/app/catalog/addOrEdit/addOrEditSpec.html
- gui/app/catalog/modals/clone/cloneSpec.html
- gui/app/catalog/modals/import/ImportSpecController.js
- gui/app/catalog/modals/import/importSpec.html
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-896
> NDS-896: Fix validation on shortName

- apiserver/cmd/server/server.go
- apiserver/pkg/email/email.go
- apiserver/pkg/kube/kube.go
- apiserver/templates/approved-email.html
* Added username to approval email
* CC support on approve/deny messages
* Allow login and password recovery using email or username
> NDS-883/943: CC support on approve/deny; login using email address

- apiserver/cmd/server/server.go
- apiserver/pkg/kube/kube.go
https://opensource.ncsa.illinois.edu/jira/browse/NDS-355
* Added support for multiple hosts/ports in ingress rule
> NDS-355: Added support for multiple ports

- gui/app/catalog/addOrEdit/AddOrEditSpecController.js
- gui/app/catalog/addOrEdit/addOrEditSpec.html
Due to a recent support request, adding this field back
> Add logo field back to addOrEditSpec

- apiserver/cmd/server/server.go
- apiserver/entrypoint.sh
- apiserver/pkg/config/config.go
- apiserver/pkg/kube/kube.go
* Added SHARED_VOLUME_READ_ONLY environment variable
* Added readOnly option to config
* If true, extra volumes are mounted  read-only in containers
> NDS-980: Add support for mounting shared folders as readonly

- apiserver/pkg/kube/kube.go
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-952
> NDS-952: No default tag causes API Server to crash

- apiserver/cmd/server/server.go
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-1037
> NDS-1037: Added check for approved accounts only on init

- apiserver/cmd/server/server.go
- apiserver/pkg/kube/kube.go
https://github.com/craig-willis/ndslabs/tree/NDS-1069
> NDS-1069: Do not include port in single-port spec ingress hosts

- gui/app/login/signUp/SignUpController.js
- gui/app/login/signUp/signUp.html
* Escape regex operators in new passwords
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-1035
> NDS-1035: Creating user account with password that ends in $

- apiserver/Dockerfile
- apiserver/cmd/server/server.go
- apiserver/entrypoint.sh
- apiserver/glide.yaml
- apiserver/pkg/apictl/client/client.go
- apiserver/pkg/apictl/cmd/quickstart.go
- apiserver/pkg/apictl/cmd/root.go
- apiserver/pkg/email/email.go
- apiserver/pkg/etcd/etcd.go
- apiserver/pkg/kube/kube.go
- apiserver/pkg/types/types.go
- apiserver/templates/approved-email.html
* Updated Dockerfile to use new chained builds and updated glide dependencies
* NDS-1041: Updated CreateBasicAuthSecret to add email address to secret and case-insensitive email checks
* NDS-1097: Added quickstart endpoint, client command, and "nexturl" to registration/approval process
> NDS-1041/1097/1099: Add email address to basic auth secret.

- apiserver/cmd/server/server.go
- apiserver/entrypoint.sh
- apiserver/glide.yaml
- apiserver/pkg/config/config.go
- apiserver/pkg/kube/kube.go
Also included:
* Preliminary authorization for given token + host name
* Fixed connection leak in watch methods
* Fixed build errors due to glide.yaml change
> NDS-1118: Added support for external auth annotations

- gui/dashboard/DashboardModule.js
- gui/dashboard/dashboard/DashboardController.js
- gui/landing/LandingModule.js
- gui/login/static/LoginController.js
- gui/login/static/LoginModule.js
- gui/shared/services.js
See https://opensource.ncsa.illinois.edu/jira/browse/NDS-1136
> NDS-1136: Fix double pop-up during quickstart

- gui/dashboard/catalog/catalog.html
- gui/shared/services.js
* Adjusted wording for quickstart link buttons
* Added a "framename" for quickstart navigation to prevent multiple tabs opening to the same service
> Minor quickstart adjustments

- apiserver/Dockerfile.test
- apiserver/build.sh
- apiserver/cmd/server/server.go
- apiserver/cmd/server/server_test.go
- apiserver/entrypoint.sh
- apiserver/glide.yaml
* Added interrupt signal handling to http server
* Added simply main test (server_test.go) for coverage analysis
* Added build process (build.sh) and image creation process (Dockerfile.test) to build API server and Docker image with coverage instrumentation
* Added a TEST environment variable to control whether apiserver runs in coverage mode
> NDS-1146: API server coverage build process

- apiserver/cmd/server/server.go
See:
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-1177
* https://opensource.ncsa.illinois.edu/jira/browse/NDS-1219
> NDS-1219 / NDS-1177: StartStack should return 202 if starting, prevent duplicate ingress on auth toggle

- gui/server.js
Fixes #276 
Should be reviewed with https://github.com/nds-org/workbench-helm-chart/pull/12
> Read subdomain_prefix from env instead of 'www'

- gui/login/static/LoginController.js
> Use Catalog as default page when first logging in

- gui/dashboard/catalog/catalog.html
- gui/dashboard/dashboard/console/console.html
- gui/dashboard/dashboard/dashboard.html
- gui/dashboard/dashboard/service/addOrEditService.html
- gui/shared/navbar/navbar.html
* Update Dashboard/Applications page names throughout
* Highlight current page in navbar
Fixes #298
> Consistent naming, highlight active navbar item

- gui/dashboard/catalog/catalog.html
> Catalog: Remove help icon, revise text in help link on dropdown

- gui/dashboard/catalog/catalog.html
> Catalog: Hide 'Add' button after installing once, highlight the 'View' button

- gui/dashboard/dashboard/dashboard.html
> Added description to Dashboard page, changed red panels to grey

- gui/landing/LandingModule.js
Landing HTML isn't ever populated from `env.json`
* Fetch `env.json` from Landing page and use it to populate missing variables
> Fix landingpage envjson bug

- .github/workflows/docker.yml
To be able to push you need to set 
- GHCR_USERNAME = your github username
- GHCR_PASSWORD = secert to write to packages only
- DOCKERHUB_USERNAME = username to write to docker (we created a new user for clowder)
- DOCKERHUB_PASSWORD = password to write to docker
> docker github action

- apiserver/build.sh
- apiserver/cmd/server/server.go
- apiserver/entrypoint.sh
- gui/ConfigModule.js
- gui/Dockerfile
- gui/package-lock.json
- gui/package.json
- gui/swagger.yaml
Changes:
* Security upgrades for various NPM packages
* Bug fix for `defaultPath=/` edge case (for dev environments)
> Release 1.3.1

- apiserver/build.sh
- apiserver/pkg/kube/kube.go
- gui/ConfigModule.js
- gui/Dockerfile
- gui/package-lock.json
- gui/package.json
- gui/swagger.yaml
Changes:
* Better support for Traefik ingress controller (remove NGINX-specific annotations)
> Release 1.3.2
